core_homepage:
    path:     /
    defaults: { _controller: CoreBundle:Default:index }

core_contact:
    path: /contact
    defaults: { _controller: CoreBundle:Contact:contact }

core_test:
    path: /test
    defaults: { _controller: CoreBundle:Default:test}