services:
  oc_platform.antispam:
    class: OC\PlatformBundle\Antispam\OCAntispam
    arguments:
      - "@mailer"
      - "%locale%"
      - 50
  oc_platform_service_mailer.application_mailer:
    class: OC\PlatformBundle\Service\Mailer\ApplicationMailer
    arguments:
      - "@mailer"
  oc_platform_doctrine_listener.application_creation_listener:
    class: OC\PlatformBundle\DoctrineListener\ApplicationCreationListener
    arguments:
      - "@oc_platform_service_mailer.application_mailer"
    tags:
      - { name: doctrine.event_listener, event: postPersist }
  OC\PlatformBundle\DataFixtures\ORM\LoadCategory:
      tags: [doctrine.fixture.orm]
  OC\PlatformBundle\DataFixtures\ORM\LoadSkill:
    tags: [doctrine.fixture.orm]
