<?php

namespace OC\PlatformBundle\Repository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getApplicationsWithAdvert(int $limit)
    {
        $queryBuilder = $this->createQueryBuilder('app')
            ->innerJoin('app.advert', 'a')
            ->setMaxResults($limit);

        return $queryBuilder->getQuery()->getResult();
    }
}
