<?php

namespace OC\PlatformBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get query builder for like querries on category name
     *
     * @param string $pattern
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getLikeQueryBuilder(string $pattern)
    {
        return $this->createQueryBuilder('c')
            ->where('c.name LIKE :pattern')
            ->setParameter('pattern', $pattern);
    }
}
